### ISSUE TITLE
Extract headings from <span class="h1"> <span class="h2"> etc

### ISSUE THREAD

**Issue by netjeff** [earshinov/tocit#6]
On some pages that have headings visually, tocit does not seem to "see" them.  The most notable is example are the official rfc pages from IETF, like https://datatracker.ietf.org/doc/html/rfc7230 which is the rfc for http 1.1.  Looking at the html source, the rfc pages don't use \<h1> \<h2> etc, instead the html uses \<span class="h1"> \<span class="h2"> etc.  I'm thinking that this is why tocit does not extract headings.

I'm thinking about working on this myself, but though I'd also open an issue in case someone else wants to take a look.

**Comment by earshinov** [comment]
Hey! Tocit only recognizes standard HTML tags (`<h1>`...`<h6>`). CSS classes as in `<span class="h1">` are arbitrary and have no semantic meaning. They could just as well be `<span class="header-level-one">`. I don't think supporting them in tocit is a good idea. Nothing prevents website authors from using semantic `<h1>...<h6>` tags instead of or in addition to CSS classes. I am afraid, if you want these sites supported right now, you will have to fork tocit.

**Comment by netjeff** [comment]
Thanks for your consideration.  Agreed that relying on span classes is a hack.  If I fork my own to do this, I'll leave a comment back here.
